config/routes.rb
Rails.application.routes.draw do
  resources :borrows

  resources :fines

  resources :members

  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/borrow.rb
class Borrow < ActiveRecord::Base
  belongs_to :book_no
  belongs_to :member
  belongs_to :fine_type
end

app/models/fine.rb
class Fine < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_no, :title)
    end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :set_borrow, only: [:show, :edit, :update, :destroy]

  # GET /borrows
  # GET /borrows.json
  def index
    @borrows = Borrow.all
  end

  # GET /borrows/1
  # GET /borrows/1.json
  def show
  end

  # GET /borrows/new
  def new
    @borrow = Borrow.new
  end

  # GET /borrows/1/edit
  def edit
  end

  # POST /borrows
  # POST /borrows.json
  def create
    @borrow = Borrow.new(borrow_params)

    respond_to do |format|
      if @borrow.save
        format.html { redirect_to @borrow, notice: 'Borrow was successfully created.' }
        format.json { render :show, status: :created, location: @borrow }
      else
        format.html { render :new }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borrows/1
  # PATCH/PUT /borrows/1.json
  def update
    respond_to do |format|
      if @borrow.update(borrow_params)
        format.html { redirect_to @borrow, notice: 'Borrow was successfully updated.' }
        format.json { render :show, status: :ok, location: @borrow }
      else
        format.html { render :edit }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrows/1
  # DELETE /borrows/1.json
  def destroy
    @borrow.destroy
    respond_to do |format|
      format.html { redirect_to borrows_url, notice: 'Borrow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrow
      @borrow = Borrow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrow_params
      params.require(:borrow).permit(:issue_dete, :returune_dete, :book_no_id, :member_id, :fine_type_id)
    end
end

app/controllers/fines_controller.rb
class FinesController < ApplicationController
  before_action :set_fine, only: [:show, :edit, :update, :destroy]

  # GET /fines
  # GET /fines.json
  def index
    @fines = Fine.all
  end

  # GET /fines/1
  # GET /fines/1.json
  def show
  end

  # GET /fines/new
  def new
    @fine = Fine.new
  end

  # GET /fines/1/edit
  def edit
  end

  # POST /fines
  # POST /fines.json
  def create
    @fine = Fine.new(fine_params)

    respond_to do |format|
      if @fine.save
        format.html { redirect_to @fine, notice: 'Fine was successfully created.' }
        format.json { render :show, status: :created, location: @fine }
      else
        format.html { render :new }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fines/1
  # PATCH/PUT /fines/1.json
  def update
    respond_to do |format|
      if @fine.update(fine_params)
        format.html { redirect_to @fine, notice: 'Fine was successfully updated.' }
        format.json { render :show, status: :ok, location: @fine }
      else
        format.html { render :edit }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fines/1
  # DELETE /fines/1.json
  def destroy
    @fine.destroy
    respond_to do |format|
      format.html { redirect_to fines_url, notice: 'Fine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fine
      @fine = Fine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fine_params
      params.require(:fine).permit(:fine_type, :fine_amunt)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:member_name, :meber_nicn)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_no %><br>
    <%= f.text_field :book_no %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Book no</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.book_no %></td>
        <td><%= book.title %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book no:</strong>
  <%= @book.book_no %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/borrows/_form.html.erb
<%= form_for(@borrow) do |f| %>
  <% if @borrow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@borrow.errors.count, "error") %> prohibited this borrow from being saved:</h2>

      <ul>
      <% @borrow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issue_dete %><br>
    <%= f.text_field :issue_dete %>
  </div>
  <div class="field">
    <%= f.label :returune_dete %><br>
    <%= f.text_field :returune_dete %>
  </div>
  <div class="field">
    <%= f.label :book_no_id %><br>
    <%= f.text_field :book_no_id %>
  </div>
  <div class="field">
    <%= f.label :member_id %><br>
    <%= f.text_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :fine_type_id %><br>
    <%= f.text_field :fine_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/borrows/edit.html.erb
<h1>Editing Borrow</h1>

<%= render 'form' %>

<%= link_to 'Show', @borrow %> |
<%= link_to 'Back', borrows_path %>

app/views/borrows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Borrows</h1>

<table>
  <thead>
    <tr>
      <th>Issue dete</th>
      <th>Returune dete</th>
      <th>Book no</th>
      <th>Member</th>
      <th>Fine type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @borrows.each do |borrow| %>
      <tr>
        <td><%= borrow.issue_dete %></td>
        <td><%= borrow.returune_dete %></td>
        <td><%= borrow.book_no %></td>
        <td><%= borrow.member %></td>
        <td><%= borrow.fine_type %></td>
        <td><%= link_to 'Show', borrow %></td>
        <td><%= link_to 'Edit', edit_borrow_path(borrow) %></td>
        <td><%= link_to 'Destroy', borrow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Borrow', new_borrow_path %>

app/views/borrows/new.html.erb
<h1>New Borrow</h1>

<%= render 'form' %>

<%= link_to 'Back', borrows_path %>

app/views/borrows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Issue dete:</strong>
  <%= @borrow.issue_dete %>
</p>

<p>
  <strong>Returune dete:</strong>
  <%= @borrow.returune_dete %>
</p>

<p>
  <strong>Book no:</strong>
  <%= @borrow.book_no %>
</p>

<p>
  <strong>Member:</strong>
  <%= @borrow.member %>
</p>

<p>
  <strong>Fine type:</strong>
  <%= @borrow.fine_type %>
</p>

<%= link_to 'Edit', edit_borrow_path(@borrow) %> |
<%= link_to 'Back', borrows_path %>

app/views/fines/_form.html.erb
<%= form_for(@fine) do |f| %>
  <% if @fine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fine.errors.count, "error") %> prohibited this fine from being saved:</h2>

      <ul>
      <% @fine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fine_type %><br>
    <%= f.text_field :fine_type %>
  </div>
  <div class="field">
    <%= f.label :fine_amunt %><br>
    <%= f.text_field :fine_amunt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fines/edit.html.erb
<h1>Editing Fine</h1>

<%= render 'form' %>

<%= link_to 'Show', @fine %> |
<%= link_to 'Back', fines_path %>

app/views/fines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fines</h1>

<table>
  <thead>
    <tr>
      <th>Fine type</th>
      <th>Fine amunt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fines.each do |fine| %>
      <tr>
        <td><%= fine.fine_type %></td>
        <td><%= fine.fine_amunt %></td>
        <td><%= link_to 'Show', fine %></td>
        <td><%= link_to 'Edit', edit_fine_path(fine) %></td>
        <td><%= link_to 'Destroy', fine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fine', new_fine_path %>

app/views/fines/new.html.erb
<h1>New Fine</h1>

<%= render 'form' %>

<%= link_to 'Back', fines_path %>

app/views/fines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fine type:</strong>
  <%= @fine.fine_type %>
</p>

<p>
  <strong>Fine amunt:</strong>
  <%= @fine.fine_amunt %>
</p>

<%= link_to 'Edit', edit_fine_path(@fine) %> |
<%= link_to 'Back', fines_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RrrrApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_name %><br>
    <%= f.text_field :member_name %>
  </div>
  <div class="field">
    <%= f.label :meber_nicn %><br>
    <%= f.text_field :meber_nicn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Members</h1>

<table>
  <thead>
    <tr>
      <th>Member name</th>
      <th>Meber nicn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.member_name %></td>
        <td><%= member.meber_nicn %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member name:</strong>
  <%= @member.member_name %>
</p>

<p>
  <strong>Meber nicn:</strong>
  <%= @member.meber_nicn %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>